# For details, see https://github.com/devcontainers/images/tree/main/src/ruby
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt
